### ISSUE TITLE
Need the ability to import/export exams as standalone files

### ISSUE THREAD

**Issue by blerner** [CodeGrade/hourglass#106]

**Comment by kylesferrazza** [comment]
Entire zip upload/download?

**Comment by blerner** [comment]
Yes.  I think we need two formats: as a single massive JSON/YAML file that includes the questions and the referenced files and their marks, and as a zip file that matches the current upload format, of the questions.yaml file, and as a directory tree of referenced files

**Comment by kylesferrazza** [comment]
It would be unfortunate to have to write another big transform method to convert the saved schema back into the upload one..

Does it make more sense to be saving what is currently the upload schema (using it for uploading and saving), and then take the defaults that are placed in by the transform method and assume them in the frontend (eliminating the need for the transformation)?

**Comment by kylesferrazza** [comment]
(or just make them both use the save schema, and make `exam.yaml` files slightly more verbose?)

**Comment by blerner** [comment]
The advantage to the upload schema is ease of authorship, which boils down to the two features of  keeping the answers closely together with the questions themselves, and using a non-homogeneous tagging of question types (by using the key of the question, rather than a type field).  The advantage to the saved schema is that we clearly have them separated, and normalized into a simpler-to-process data type.

Most of the annoying complexity in the `Upload#parse_info` method is really error checking that goes beyond just simple schema checking.  The rest of it is just a simple tree-to-tree transformation.

What if we relaxed our setup slightly: 
- on input of a YAML file, we try validating it against the exam-save schema.  If that works, cool, use it.  If not, try validating it against the exam-upload schema.  If that works, cool, transform it as we currently do.  If that fails, reject.
- on output, always output in the exam-save format

The main thing I want to preserve in the export format is the professor's choice of whether to produce a standalone directory tree of referenced files, or a post-processed `info` hash of them.  The post-processed form isn't easily editable and reusable, and I doubt professors will want to use it.

**Comment by kylesferrazza** [comment]
Yes that strategy makes sense, we just will need a method to transform our jsonb `files` field to a directory of real files in a zip.
