### ISSUE TITLE
Scrolling issues

### ISSUE THREAD

**Issue by kylesferrazza** [CodeGrade/hourglass#122]
Lots of weird scrolling issues..
- https://reacttraining.com/react-router/web/guides/scroll-restoration/scroll-to-top
- https://stackoverflow.com/a/50828050/783424 for the weird scrolling issues

**Comment by blerner** [comment]
Thematically related, but not quite the same root problem: the CM instances in the "Preview files" dropdowns in the exam editor almost always seem to be scrolled down by ~page worth...  not anywhere near as important as fixing the overall page scrolling, though

**Comment by kylesferrazza** [comment]
Fixed by #132
