### ISSUE TITLE
Add matchbrackets to codemirror

### ISSUE THREAD

**Issue by kylesferrazza** [CodeGrade/hourglass#126]
We tried adding it originally in b8bad607a55d731d152dbd6439f5d0c0b71fec83 and ran into https://github.com/CodeGrade/hourglass/pull/117#issuecomment-646685651.

**Comment by blerner** [comment]
We don't have to completely remove matchbrackets right now; we just need to filter the `marksToDescs` function to only look for _our_ marks, which we can do by searching for the classname we picked.  We also need to filter on that class name in Code.tsx where we're checking if the current text is marked (and therefore locked) already or not.
