### ISSUE TITLE
Add a timer alert to the exam

### ISSUE THREAD

**Issue by blerner** [CodeGrade/hourglass#2]
Students should be able to easily see how much time remains. UI idea: a clock icon in an "info" outline bubble, and when students hover over it, it expands to give time remaining. At each half-hour mark it could flash briefly, and then at the 10, 5, 1-minute marks, turn yellow, orange, red.

We would obviously need to encode when the exam is "over", or how long it is, for this to work...

**Comment by blerner** [comment]
See work being done in #53.

**Comment by kylesferrazza** [comment]
Should I add new `exam` fields directly to the `create_exams` migration?

I'm thinking we probably don't need to add a migration for adding a single field since the app is not used in production yet - we can both just reset and re-seed our databases.

**Comment by kylesferrazza** [comment]
> an exam policy will need to say "You may take H number of hours, starting at S and ending no later than E"

> or M number of minutes

**Comment by blerner** [comment]
I don't mind if you modify that migration, that's fine.  But we do need to figure out what those fields need to be, and I can't seem to find the comment where we wrote down our initial ideas...

**Comment by kylesferrazza** [comment]
> as part of the yaml file, or part of the exam-creation workflow
