### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by kylesferrazza** [CodeGrade/hourglass#23]
Make a logo, add it to:
- favicon
- readme
- navbar

**Comment by pfourrier** [comment]
hello, what do you want exactly?

**Comment by blerner** [comment]
A vectorized, smaller version of https://commons.wikimedia.org/wiki/File:Lagenorhynchus_cruciger_1847_-_cropping.jpg might be our best bet (that seems to be the cleanest, public-domain image out there)...

**Comment by blerner** [comment]
```
wget https://commons.wikimedia.org/wiki/File:Lagenorhynchus_cruciger_1847_-_cropping.jpg -O hourglass-dolphin.jpeg
convert hourglass-dolphin.jpg -fuzz 10% -fill none -draw "color 1x1 floodfill" hourglass-dolphin.png
convert hourglass-dolphin.png -flop -background none -resize 129x129 -gravity center -extent 129x129 site-icon.png
```
