### ISSUE TITLE
Can't Copy from Student and Rubric Code Answers

### ISSUE THREAD

**Issue by cjcodell1** [CodeGrade/hourglass#232]
When grading, copying content works from the question prompt (which I think is a CodeMirror box), but it does not work in the student's code response and rubric code (which are also CodeMirror boxes).  Copying from a normal text box works fine.

**Comment by blerner** [comment]
Fixed by https://github.com/CodeGrade/hourglass/commit/8431e73dcc74faf0bec059acfb2214c3b296b9e0
