### ISSUE TITLE
Tooltip flickering

### ISSUE THREAD

**Issue by kylesferrazza** [CodeGrade/hourglass#356]
[14:35] Lerner, Ben
Note for future: look into adding `container={document.body}` onto the Tooltip OverlayTrigger, to avoid the flickering effect

**Comment by blerner** [comment]
That `container` approach doesn't work at all.

It seems the problem may be related to https://github.com/react-bootstrap/react-bootstrap/pull/6348.  I have an attempt at fixing this, which is ugly but seems to work...

**Comment by kylesferrazza** [comment]
Trying to remember how to repro this?

**Comment by blerner** [comment]
Hover the mouse over e.g. the preflight tabs, and move the mouse so it just barely is in the triangle of the tooltip itself -- that'll help the tooltip flicker on and off rapidly, then look to the upper-left corner of the screen.
