### ISSUE TITLE
Performance with React contexts

### ISSUE THREAD

**Issue by blerner** [CodeGrade/hourglass#36]
Using React.createContext with textual inputs (Text and Code) causes incredibly slow performance for me, on both Firefox and Chrome.  We need to come up with a better approach for stashing the answer snapshots.

**Comment by kylesferrazza** [comment]
https://redux.js.org/basics/usage-with-react

**Comment by blerner** [comment]
This seems slightly better now than when I opened this issue (in that the Reactify branch is doing better things overall).  I'm still seeing a performance dropoff for long lines of text, and I *think* it's because either CodeMirror has to re-tokenize the entire line, or the browser is attempting to spell-check the entire line.  If there are more spaces in the line than just mashing on keys, the performance is ... tolerably fine, for now.

**Comment by kylesferrazza** [comment]
PEBKAC
(problem exists between keyboard and _computer_)
