### ISSUE TITLE
[BUG]: "Jump to" page navigation (sidebar) does not highlight the correct question

### ISSUE THREAD

**Issue by RishikeshNK** [CodeGrade/hourglass#467]
The "Jump to" section to navigate to different questions on the exam does not correctly highlight the question when you click on the question. For instance, in the image below, I've clicked on "Question 3" (with "Toggle pagination" turned off), however, "Question 3" is not highlighted (navigation works as intended given that the page scrolls to Question 3 correctly).

Browser: Firefox

**Reference:**
![Untitled design](https://github.com/CodeGrade/hourglass/assets/63854326/c1049d8c-33f5-495a-8d46-7b9973343a8e)

**Comment by blerner** [comment]
This is not *quite* a bug, but rather simply how scrolling works. In your screenshot, Question 3 starts in the middle of the screen, and the top of the screen is indeed Question 2. If you were to scroll far enough that *only* Question 3 is visible, then the highlighting in the Jump To outline would update accordingly.
